name: small_models_sp26
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pip:
      - anthropic
      - gdown
      - gradio
      - huggingface-hub
      - ipykernel
      - jupyterlab
      - langchain
      - llama-cpp-python
      - matplotlib
      - numpy
      - openai
      - pandas
      - python-dotenv
      - seaborn
      - sentence-transformers
      - transformers
